Algoritmo "Natacao"


Var
   Id:inteiro


Inicio
      escreval("Digite sua idade")
      leia(Id)
      se (Id>=5) e (Id<=7) entao
      escreval("Infantil A")
      senao
      se (Id>=7) e (Id<=10) entao
      escreval("Infantil B")
      senao
      se (Id>=11) e (Id<=13) entao
      escreval("Juvenil A")
      senao
      se (Id>=14) e (Id<=17) entao
      escreval("Juvenil B")
      senao
      escreval("Adulto")
      fimse
      fimse
      fimse
      fimse


Fimalgoritmo